# Copyright (c) 2021-2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y

CONFIG_ZMK_KEYBOARD_NAME="KB_TOUCAN"
CONFIG_ZMK_MACRO_DEFAULT_WAIT_MS=5
CONFIG_ZMK_MACRO_DEFAULT_TAP_MS=5